name: pipeline-deploy-s3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc
      - run: pandoc README.md -f markdown -t html -s -o index.html
      - run: ls -la
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: index.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: ${{ vars.BUCKET_S3 }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: ./site
      - run: ls -la ./site
      - run: aws s3 cp ./site/index.html s3://$BUCKET_S3/index.html --acl public-read
